import type { EffectiveTarget, GoalSettingsInput, NutritionTarget } from '@formtally/api-contract/goals'
import * as goalsApi from '../../services/goals'
import { accountStore } from '../../stores/account'

const modes = ['automatic', 'manual'] as const
const objectives = ['fat_loss', 'maintain', 'muscle_gain'] as const
const paces = ['slow', 'standard', 'fast'] as const

Page({
  data: { mode: 'automatic' as 'automatic' | 'manual', modeLabels: ['自动估算', '手动设置'], modeIndex: 0, objective: 'fat_loss', objectiveLabels: ['减脂', '保持', '增肌'], objectiveIndex: 0, pace: 'standard', paceLabels: ['慢速', '标准', '快速'], paceIndex: 1, manual: { energyKcal: 2000, proteinGrams: 100, carbGrams: 250, fatGrams: 60 } as NutritionTarget, revision: undefined as number | undefined, preview: null as EffectiveTarget | null, error: '', message: '', busy: false },
  input(includeRevision = false): GoalSettingsInput { const expectedRevision = includeRevision ? this.data.revision : undefined; return this.data.mode === 'automatic' ? { mode: 'automatic', automatic: { objective: this.data.objective as 'fat_loss' | 'maintain' | 'muscle_gain', ...(this.data.objective === 'maintain' ? {} : { pace: this.data.pace as 'slow' | 'standard' | 'fast' }) }, manual: null, expectedRevision } : { mode: 'manual', automatic: null, manual: { target: { ...this.data.manual } }, expectedRevision } },
  async onLoad() { try { const { settings } = await goalsApi.getGoals(); if (!settings) return; if (settings.mode === 'automatic' && settings.automatic) { const pace = settings.automatic.pace ?? 'standard'; this.setData({ mode: settings.mode, modeIndex: modes.indexOf(settings.mode), objective: settings.automatic.objective, objectiveIndex: objectives.indexOf(settings.automatic.objective), pace, paceIndex: paces.indexOf(pace), revision: settings.revision }) } else if (settings.mode === 'manual' && settings.manual) this.setData({ mode: settings.mode, modeIndex: modes.indexOf(settings.mode), manual: settings.manual.target, revision: settings.revision }) } catch (error) { this.setData({ error: error instanceof Error ? error.message : '加载失败' }) } },
  mode(event: { detail: { value: string } }) { const modeIndex = Number(event.detail.value); this.setData({ mode: modes[modeIndex] ?? 'automatic', modeIndex }) }, objective(event: { detail: { value: string } }) { const objectiveIndex = Number(event.detail.value); this.setData({ objective: objectives[objectiveIndex] ?? 'fat_loss', objectiveIndex }) }, pace(event: { detail: { value: string } }) { const paceIndex = Number(event.detail.value); this.setData({ pace: paces[paceIndex] ?? 'standard', paceIndex }) },
  manual(event: { currentTarget: { dataset: { field?: string } }; detail: { value: string } }) { const target = this.data.manual; const field = event.currentTarget.dataset.field as keyof NutritionTarget; if (field) target[field] = Number(event.detail.value); this.setData({ manual: target }) },
  async preview() { this.setData({ busy: true, error: '', message: '' }); try { this.setData({ preview: (await goalsApi.previewGoal(this.input())).preview }) } catch (error) { this.setData({ error: error instanceof Error ? error.message : '预览失败' }) } finally { this.setData({ busy: false }) } },
  async save() { this.setData({ busy: true }); const ok = await accountStore.saveGoal(this.input(true)); this.setData({ busy: false, error: accountStore.state.error, message: ok ? '目标已保存，将从下一个本地日期生效。' : '' }) },
})
