<script setup lang="ts">
import type { EffectiveTarget, GoalSettingsInput, NutritionTarget } from '@formtally/api-contract/goals'
import { onMounted, ref } from 'vue'
import { getGoals, previewGoal, saveGoal } from '../../api/goals'
import GoalCalculation from '../../components/GoalCalculation.vue'

const mode=ref<'automatic'|'manual'>('automatic'),objective=ref<'fat_loss'|'maintain'|'muscle_gain'>('fat_loss'),pace=ref<'slow'|'standard'|'fast'>('standard'),manual=ref<NutritionTarget>({energyKcal:2000,proteinGrams:100,carbGrams:250,fatGrams:60}),revision=ref<number>(),preview=ref<EffectiveTarget|null>(null),busy=ref(false),error=ref(''),message=ref('')
function input(includeRevision=false):GoalSettingsInput{const expectedRevision=includeRevision?revision.value:undefined;return mode.value==='automatic'?{mode:'automatic',automatic:{objective:objective.value,...(objective.value==='maintain'?{}:{pace:pace.value})},manual:null,expectedRevision}:{mode:'manual',automatic:null,manual:{target:{...manual.value}},expectedRevision}}
onMounted(async()=>{try{const result=await getGoals();const settings=result.settings;if(!settings)return;revision.value=settings.revision;mode.value=settings.mode;if(settings.mode==='automatic'&&settings.automatic){objective.value=settings.automatic.objective;pace.value=settings.automatic.pace??'standard'}if(settings.mode==='manual'&&settings.manual)manual.value={...settings.manual.target}}catch(cause){error.value=cause instanceof Error?cause.message:'加载失败'}})
async function showPreview(){busy.value=true;error.value='';try{preview.value=(await previewGoal(input())).preview}catch(cause){error.value=cause instanceof Error?cause.message:'预览失败'}finally{busy.value=false}}
async function save(){busy.value=true;error.value='';try{const result=await saveGoal(input(true));revision.value=result.settings.revision;preview.value=result.effectiveTarget;message.value=`目标已保存，将从 ${result.effectiveTarget.effectiveFrom} 生效；今天与历史目标不变。`}catch(cause){error.value=cause instanceof Error?cause.message:'保存失败'}finally{busy.value=false}}
</script>
<template><main class="page"><RouterLink to="/me">← 返回我的</RouterLink><h1>每日目标</h1><p class="notice">修改从下一个本地日期生效，今天与历史记录继续使用原目标。</p><form @submit.prevent="showPreview"><label>目标模式<select v-model="mode"><option value="automatic">自动估算</option><option value="manual">手动设置</option></select></label><template v-if="mode==='automatic'"><label>当前目标<select v-model="objective"><option value="fat_loss">减脂</option><option value="maintain">保持</option><option value="muscle_gain">增肌</option></select></label><label v-if="objective!=='maintain'">速度<select v-model="pace"><option value="slow">慢速</option><option value="standard">标准</option><option value="fast">快速</option></select></label></template><template v-else><label>热量（kcal）<input v-model.number="manual.energyKcal" type="number"></label><label>蛋白质（g）<input v-model.number="manual.proteinGrams" type="number"></label><label>碳水（g）<input v-model.number="manual.carbGrams" type="number"></label><label>脂肪（g）<input v-model.number="manual.fatGrams" type="number"></label></template><button type="submit" :disabled="busy">预览修改</button></form><section v-if="preview" class="result"><h2>{{ preview.effectiveFrom }} 生效</h2><p>{{ preview.target.energyKcal }} 千卡 · 蛋白质 {{ preview.target.proteinGrams }}g · 碳水 {{ preview.target.carbGrams }}g · 脂肪 {{ preview.target.fatGrams }}g</p><GoalCalculation v-if="preview.calculation" :calculation="preview.calculation"/><p v-for="warning in preview.warnings" :key="warning">{{ warning }}</p><button type="button" :disabled="busy" @click="save">确认保存</button></section><p v-if="error" role="alert">{{ error }}</p><p v-if="message" role="status">{{ message }}</p></main></template>
<style scoped>.page{width:min(100%,34rem);min-height:100svh;margin:auto;padding:1.25rem;display:grid;align-content:start;gap:1rem}.page>a{min-height:44px;display:flex;align-items:center;color:#155e4e}.page h1{margin:0}.notice{padding:.75rem;border-radius:.75rem;background:#fff2d8}form,label,.result{display:grid;gap:.5rem}form{gap:.9rem}input,select,button{min-height:48px;padding:0 .75rem;border:1px solid #cbd5d1;border-radius:.75rem;font:inherit}button{border:0;color:#fff;background:#155e4e;font-weight:700}.result{padding:1rem;border-radius:1rem;background:#fff}.result h2{margin:0}</style>
