<script setup lang="ts">
import type { Profile, ProfileInput } from '@formtally/api-contract/profile'
import { validateProfile } from '@formtally/domain/profile-validation'
import { onMounted, ref } from 'vue'
import { getProfile, saveProfile } from '../../api/profile'

const form=ref<ProfileInput|null>(null),busy=ref(false),error=ref(''),message=ref('')
onMounted(async()=>{try{const result=await getProfile();if(result.profile)form.value={...result.profile,healthContext:{...result.profile.healthContext},expectedRevision:result.profile.revision}}catch(cause){error.value=cause instanceof Error?cause.message:'加载失败'}})
async function save(){if(!form.value)return;const errors=validateProfile(form.value);if(Object.keys(errors).length){error.value=Object.values(errors)[0]!;return}busy.value=true;error.value='';try{const result=await saveProfile(form.value);const value=result.profile as Profile;if(value)form.value={...value,healthContext:{...value.healthContext},expectedRevision:value.revision};message.value='资料已保存；自动目标如有变化，将从下一个本地日期生效。'}catch(cause){error.value=cause instanceof Error?cause.message:'保存失败'}finally{busy.value=false}}
</script>
<template><main class="page"><RouterLink to="/me">← 返回我的</RouterLink><h1>身体资料与时区</h1><p class="notice">修改资料不会改写今天和历史目标；自动目标变化从下一个本地日期生效。</p><form v-if="form" @submit.prevent="save"><label>生理性别<select v-model="form.biologicalSex"><option value="male">男性</option><option value="female">女性</option></select></label><label>出生日期<input v-model="form.birthDate" type="date"></label><label>身高（cm）<input v-model.number="form.heightCm" type="number" min="100" max="250" step="0.1"></label><label>体重（kg）<input v-model.number="form.weightKg" type="number" min="25" max="350" step="0.1"></label><label>活动水平<select v-model="form.activityLevel"><option value="sedentary">久坐</option><option value="light">轻度</option><option value="moderate">中度</option><option value="high">高度</option><option value="very_high">极高</option></select></label><label>时区<input v-model="form.timezone"></label><fieldset><legend>健康状态</legend><label><input v-model="form.healthContext.pregnant" type="checkbox">孕期</label><label><input v-model="form.healthContext.breastfeeding" type="checkbox">哺乳期</label><label><input v-model="form.healthContext.clinicalDietRequired" type="checkbox">需要疾病膳食管理</label></fieldset><p v-if="error" role="alert">{{ error }}</p><p v-if="message" role="status">{{ message }}</p><button type="submit" :disabled="busy">{{ busy?'保存中…':'保存资料' }}</button></form><p v-else-if="!error" role="status">正在加载资料…</p><p v-else role="alert">{{ error }}</p></main></template>
<style scoped>.page{width:min(100%,34rem);min-height:100svh;margin:auto;padding:1.25rem;display:grid;align-content:start;gap:1rem}.page>a{min-height:44px;display:flex;align-items:center;color:#155e4e}.page h1{margin:0}.notice{padding:.75rem;border-radius:.75rem;background:#fff2d8}form,label{display:grid;gap:.4rem}form{gap:.9rem}input,select,button{min-height:48px;padding:0 .75rem;border:1px solid #cbd5d1;border-radius:.75rem;font:inherit}fieldset label{display:flex;align-items:center;min-height:44px}fieldset input{min-height:auto}button{border:0;color:#fff;background:#155e4e;font-weight:700}</style>
