<script setup lang="ts">
import type { MealItem } from '@formtally/api-contract/analyses'
import { scaleNutrition } from '@formtally/domain/meal-editor'
const props = defineProps<{ items: MealItem[] }>()
const emit = defineEmits<{ 'update:items': [items: MealItem[]] }>()
function update(index:number, patch:Partial<MealItem>){emit('update:items',props.items.map((item,i)=>i===index?{...item,...patch}:item))}
function grams(index:number,event:Event){const value=Number((event.target as HTMLInputElement).value);const item=props.items[index]!;update(index,{grams:value,nutrition:item.basisPer100Grams?scaleNutrition(item.basisPer100Grams,value):item.nutrition,origin:item.origin==='ai'?'ai_modified':item.origin})}
function nutrition(index:number,key:keyof MealItem['nutrition'],event:Event){const item=props.items[index]!;update(index,{nutrition:{...item.nutrition,[key]:Number((event.target as HTMLInputElement).value)},origin:item.origin==='ai'?'ai_modified':item.origin})}
function remove(index:number){emit('update:items',props.items.filter((_,i)=>i!==index))}
function add(){emit('update:items',[...props.items,{draftItemId:null,name:'',grams:100,nutrition:{energyKcal:0,proteinGrams:0,carbGrams:0,fatGrams:0},basisPer100Grams:null,origin:'manual',confidence:null,assumption:null}])}
</script>
<template><section class="editor"><article v-for="(item,index) in items" :key="item.draftItemId??index" class="food"><div class="heading"><input :name="`name-${index}`" :value="item.name" aria-label="食物名称" @input="update(index,{name:($event.target as HTMLInputElement).value})"><button type="button" class="text" @click="remove(index)">删除</button></div><label>重量（克）<input :name="`grams-${index}`" type="number" min="0.1" max="10000" step="0.1" :value="item.grams" @input="grams(index,$event)"></label><p v-if="item.confidence==='low'" class="warning">低置信度 · {{ item.assumption||'请核对' }}</p><div class="nutrition"><label>千卡<input type="number" :value="item.nutrition.energyKcal" @input="nutrition(index,'energyKcal',$event)"></label><label>蛋白质<input type="number" step="0.1" :value="item.nutrition.proteinGrams" @input="nutrition(index,'proteinGrams',$event)"></label><label>碳水<input type="number" step="0.1" :value="item.nutrition.carbGrams" @input="nutrition(index,'carbGrams',$event)"></label><label>脂肪<input type="number" step="0.1" :value="item.nutrition.fatGrams" @input="nutrition(index,'fatGrams',$event)"></label></div></article><button type="button" class="add" @click="add">＋ 添加食物</button></section></template>
<style scoped>.editor,.food{display:grid;gap:.8rem}.food{padding:1rem;border:1px solid #e1e8e5;border-radius:1rem;background:white}.heading{display:flex;gap:.5rem}.heading input{flex:1;font-weight:700}.nutrition{display:grid;grid-template-columns:1fr 1fr;gap:.6rem}label{display:grid;gap:.3rem;color:var(--ft-color-text-muted);font-size:.84rem}input,button{min-height:44px;border:1px solid #dbe4e0;border-radius:.7rem;padding:0 .65rem;font:inherit}.text{border:0;background:none;color:#a22b2b}.warning{margin:0;padding:.5rem;border-radius:.5rem;color:#8b4d00;background:#fff2d8}.add{background:#eef7f3;color:var(--ft-color-text);font-weight:700}</style>
